stages:
  - codestyle
  - test

flake8:
  stage: codestyle
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/flake8.txt
    - flake8 --verbose

black:
  stage: codestyle
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose -- .

django:
  stage: test
  image: python:3.10
  services:
    - name: postgres:15.4
      alias: postgres
      entrypoint: ["docker-entrypoint.sh", "postgres"]
  variables:
    POSTGRES_DB: $MEMOTIME_DATABASE_NAME
    POSTGRES_USER: $MEMOTIME_DATABASE_USER
    POSTGRES_PASSWORD: $MEMOTIME_DATABASE_PASSWORD
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_HOST: postgres
  coverage: '/^TOTAL.+?(\d+\%)$/'
  script:
    - apt-get update && apt-get install -y postgresql-client
    - export PGPASSWORD=$MEMOTIME_DATABASE_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"
    - pip install -r requirements/test.txt
    - cd memotime
    - python3 manage.py migrate
    - coverage run manage.py test
    - coverage report
