# Generated by Django 4.2.16 on 2024-12-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email_alter_user_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_email_subscribed",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Whether email notifications are enabled",
                verbose_name="email notifications",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_telegram_subscribed",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Whether Telegram notifications are enabled",
                verbose_name="Telegram notifications",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="subscription_end_date",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Date when the subscription ends and is deactivated",
                null=True,
                verbose_name="subscription end date",
            ),
        ),
    ]
