# Generated by Django 4.2.16 on 2024-12-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_attempts_user_last_attempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="attempts",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_attempt",
        ),
    ]
