# Generated by Django 4.2.16 on 2025-03-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0006_remove_teacher_user_remove_event_custom_name_and_more"),
        ("users", "0004_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscription_end_date",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
    ]
