# Generated by Django 4.2.16 on 2025-03-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_subscription_end_date_delete_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
