# Generated by Django 4.2.16 on 2025-03-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_telegram_subscribed",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Whether Telegram notifications are enabled",
                verbose_name="Telegram notifications",
            ),
        ),
    ]
