# Generated by Django 4.2.16 on 2024-12-09 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_start",
                    models.DateTimeField(
                        help_text="time when the day starts", verbose_name="start time"
                    ),
                ),
                (
                    "time_end",
                    models.DateTimeField(
                        help_text="time when the day ends", verbose_name="end time"
                    ),
                ),
                (
                    "even",
                    models.BooleanField(
                        help_text="shows whether week is even or odd",
                        verbose_name="even week",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="user, who owns this day schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_schedule",
                        related_query_name="time_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "time schedule",
                "verbose_name_plural": "time schedules",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="name of the teacher",
                        max_length=150,
                        verbose_name="name",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="user, who owns this day schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher",
                        related_query_name="teachers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "teacher",
                "verbose_name_plural": "teachers",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="the day, from which this schedule is active",
                        verbose_name="schedule start date",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        help_text="the day, when schedule will be destroyed",
                        verbose_name="schedule expiration date",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="user, who owns this schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        related_query_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "schedule",
                "verbose_name_plural": "schedules",
            },
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disposable",
                    models.BooleanField(
                        help_text="shows whether note is disposable or repeating",
                        verbose_name="is the note disposable",
                    ),
                ),
                (
                    "global_note",
                    models.BooleanField(
                        db_column="global",
                        help_text=(
                            "shows whether note is global (displayed on dependent"
                            " schedules) or local"
                        ),
                        verbose_name="is note global",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="heading of the note",
                        max_length=150,
                        verbose_name="heading",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text=(
                            "description of the note, that you will see in the"
                            " notification"
                        ),
                        verbose_name="description",
                    ),
                ),
                (
                    "time_link",
                    models.ForeignKey(
                        help_text="time when notification will come",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        related_query_name="notes",
                        to="schedule.timeschedule",
                        verbose_name="notification time",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="user, who owns this day schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        related_query_name="notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "note",
                "verbose_name_plural": "notes",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="name of the event",
                        max_length=150,
                        verbose_name="name",
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        help_text="custom name of the event",
                        max_length=150,
                        verbose_name="custom name",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_column="type",
                        help_text=(
                            "one of the types: subject, after-school activity, relax"
                        ),
                        max_length=20,
                        verbose_name="type of the event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="user, who owns this day schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        related_query_name="events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.CreateModel(
            name="DaySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.CharField(
                        choices=[
                            ("1", "Monday"),
                            ("2", "Tuesday"),
                            ("3", "Wednesday"),
                            ("4", "Thursday"),
                            ("5", "Friday"),
                            ("6", "Saturday"),
                            ("7", "Sunday"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        help_text="main schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_schedule",
                        related_query_name="day_schedules",
                        to="schedule.schedule",
                        verbose_name="schedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="user, who owns this day schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_schedule",
                        related_query_name="day_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "day schedule",
                "verbose_name_plural": "day schedules",
            },
        ),
    ]
