# Generated by Django 4.2.16 on 2024-12-15 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Event description",
                max_length=10000,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Note description",
                max_length=10000,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="global_note",
            field=models.BooleanField(
                default=False, help_text="Global note", verbose_name="global"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="heading",
            field=models.CharField(
                help_text="Note heading", max_length=128, verbose_name="heading"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="expiration_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Schedule expiration date",
                null=True,
                verbose_name="expiration date",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="is_static",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Determines if the schedule alternates (if False, the 'even' field"
                    " in TimeSchedule is used)"
                ),
                verbose_name="static",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Schedule start date",
                verbose_name="start date",
            ),
        ),
        migrations.AlterField(
            model_name="timeschedule",
            name="day_number",
            field=models.IntegerField(
                choices=[
                    (None, "Day"),
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ],
                help_text="Day of the week (1-7)",
                verbose_name="day of the week",
            ),
        ),
    ]
