# Generated by Django 4.2.16 on 2024-12-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_group"),
        ("schedule", "0003_alter_timeschedule_day_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="users.group",
                verbose_name="group",
            ),
        ),
    ]
