# Generated by Django 4.2.16 on 2024-12-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_schedule_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="notes",
        ),
        migrations.AddField(
            model_name="note",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Event related to the note",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="schedule.event",
            ),
        ),
    ]
