# Generated by Django 4.2.16 on 2025-03-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0005_remove_event_notes_note_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="user",
        ),
        migrations.RemoveField(
            model_name="event",
            name="custom_name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="event",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="expiration_date",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="group",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="start_date",
        ),
        migrations.AddField(
            model_name="event",
            name="disposable",
            field=models.BooleanField(
                default=True,
                help_text="Determines if the note is used only once",
                verbose_name="disposable",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="heading",
            field=models.CharField(
                default=None,
                help_text="Note heading",
                max_length=128,
                verbose_name="heading",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="timeschedule",
            name="time_end",
            field=models.TimeField(
                help_text="End time of the subject/event",
                null=True,
                verbose_name="end time",
            ),
        ),
        migrations.AlterField(
            model_name="timeschedule",
            name="time_start",
            field=models.TimeField(
                help_text="Start time of the subject/event",
                null=True,
                verbose_name="start time",
            ),
        ),
        migrations.DeleteModel(
            name="Note",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
