# Generated by Django 4.2.16 on 2025-03-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0006_remove_teacher_user_remove_event_custom_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="name",
            field=models.TextField(default=None, verbose_name="name"),
            preserve_default=False,
        ),
    ]
