# Generated by Django 4.2.16 on 2025-03-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0007_schedule_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="name",
            field=models.TextField(default="Krutoe nazvanie 2009", verbose_name="name"),
        ),
    ]
