# Generated by Django 4.2.16 on 2025-03-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0009_alter_schedule_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="name",
            field=models.TextField(
                blank=True, help_text="Text", max_length=500, verbose_name="name"
            ),
        ),
    ]
