# Generated by Django 4.2.16 on 2025-03-14 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0010_alter_schedule_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="day_number",
            field=models.IntegerField(
                choices=[
                    (None, "Day"),
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ],
                default=1,
                help_text="Day of the week (1-7)",
                verbose_name="day of the week",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="schedule",
            field=models.ForeignKey(
                help_text="Schedule",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="schedule.schedule",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="time_end",
            field=models.TimeField(
                help_text="End time of the subject/event",
                null=True,
                verbose_name="end time",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="time_start",
            field=models.TimeField(
                help_text="Start time of the subject/event",
                null=True,
                verbose_name="start time",
            ),
        ),
        migrations.DeleteModel(
            name="TimeSchedule",
        ),
    ]
