# Generated by Django 4.2.16 on 2025-03-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0011_event_day_number_event_schedule_event_time_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time_end",
            field=models.TimeField(
                blank=True,
                help_text="End time of the subject/event",
                null=True,
                verbose_name="end time",
            ),
        ),
    ]
