# Generated by Django 4.2.16 on 2025-03-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0012_alter_event_time_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="disposable",
            field=models.BooleanField(
                default=False,
                help_text="Determines if the note is used only once",
                verbose_name="disposable",
            ),
        ),
    ]
