# Generated by Django 4.2.16 on 2024-12-11 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("получено", "получено"),
                            ("в обработке", "в обработке"),
                            ("ответ дан", "ответ дан"),
                        ],
                        default="получено",
                        help_text="Статус обработки",
                        max_length=20,
                        verbose_name="статус обработки",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Содержание фидбэка",
                        max_length=10240,
                        verbose_name="текст",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата создания фидбэка",
                        verbose_name="создан",
                    ),
                ),
            ],
            options={
                "verbose_name": "фидбэк",
                "verbose_name_plural": "фидбэки",
            },
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Время изменения статуса",
                        verbose_name="время",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        db_column="from",
                        help_text="Из какого статуса",
                        max_length=20,
                        verbose_name="из статуса",
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        db_column="to",
                        help_text="В какой статус",
                        max_length=20,
                        verbose_name="в статус",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        help_text="Фидбэк, для которого изменён статус",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="feedback.feedback",
                        verbose_name="фидбэк",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="User_key",
                        help_text="Пользователь, изменивший статус",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="status_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "лог изменения статуса",
                "verbose_name_plural": "логи изменения статусов",
            },
        ),
        migrations.CreateModel(
            name="PersonalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        help_text="Автор фидбэка",
                        max_length=100,
                        null=True,
                        verbose_name="имя",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        help_text="Почта автора фидбэка",
                        max_length=200,
                        verbose_name="почта",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пользователь, отправивший фидбек",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feedback",
            name="personal_data",
            field=models.OneToOneField(
                default=None,
                help_text="Персональные данные автора",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feedback",
                to="feedback.personaldata",
                verbose_name="персональные данные",
            ),
        ),
    ]
